### ISSUE TITLE
Taxation system must fetch users before choosing one

### ISSUE THREAD

**Issue by loockeeer** [Les-Laboratoires/lab-tools#20]
In src/listeners/ready.js, you call guild.members.cache.array() but calling this could lead to some issues because all the users in the guild may not be cached. 

That's why using await guild.members.fetch() is more preferable

**Comment by GhomKrosmonaute** [comment]
The guild is fetched on start and my intents and my cache are perfectly configured.

A member fetching is not needed, but go PR if you want to insist (●'◡'●)

**Comment by loockeeer** [comment]
cheater
